apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: psi-perf-ds
  namespace: prometheus
spec:
  selector:
    matchLabels: 
      app: psi-perf
  template:
    metadata:
      labels:
        app: psi-perf
    spec:
      serviceAccountName: psi-perf-ds
      terminationGracePeriodSeconds: 5
      hostPID: true
      hostNetwork: true
      nodeSelector:
          kubernetes.io/os: linux
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: psi-perf-ds
          #image: t.harbor.siat.ac.cn:100/library/cgroup-sc:v3.16
          image: k.harbor.siat.ac.cn:30003/library/psi-perf-ds:v3.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 2333
            hostPort: 2333
            protocol: TCP
            name: metrics
          securityContext:
            capabilities:
              add: ["SYS_PTRACE","SYS_ADMIN"]
          env:
            - name: PORT
              value: "2333"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PSI_INTERVAL
              value: "5"
            - name: PERF_INTERVAL
              value: "5"
            - name: CGROUP_BASE_DIR
              value: "/root/cgroup"
            - name: PROC_BASE_DIR
              value: "/root/proc"
            - name: DOCKER_BASE_DIR
              value: "/root/docker"
            - name: PERF_BASE_DIR
              value: "/sys"
            - name: PERF_COLLECTOR_ENABLED
              value: "true"
            - name: PSI_COLLECTOR_ENABLED
              value: "false"
            - name: HW_PERF_LABELS
              value: "CPUCycles,Instructions,CacheRefs,CacheMisses"
            
          resources:
            requests:
              cpu: 200m
              memory: "200Mi"
            limits:
              cpu: 200m
              memory: "500Mi"
          volumeMounts:
            - name: dockerpath
              mountPropagation: HostToContainer
              mountPath: /root/docker
              readOnly: true
            - name: procpath
              mountPropagation: HostToContainer
              mountPath: /root/proc
              readOnly: true
            - name: cgrouppath
              mountPropagation: HostToContainer
              mountPath: /root/cgroup
              readOnly: true
            - name: perfpath
              mountPropagation: HostToContainer
              mountPath: /sys
              readOnly: true
      volumes:
        - name: dockerpath
          hostPath:
            path: /var/lib/docker
            type: Directory
        - name: procpath
          hostPath:
            path: /proc
            type: Directory
        - name: cgrouppath
          hostPath:
            path: /sys/fs/cgroup
            type: Directory
        - name: perfpath
          hostPath:
            path: /sys
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: psi-perf-service #this will be the Domain name
  namespace: prometheus
  labels:
    app: psi-perf
spec:
  selector:
    app: psi-perf
  ports:
    - port: 2333
      protocol: TCP